name: givenfind
version: "0.1.0.0"
synopsis: Library collecting data from text
description: Finds questions, commands and data with symbols and units from exercises of different branches (for example - physics)
category: Text
author: Jagoda "juliagoda" Górska
maintainer: juliagoda.pl@protonmail.com
copyright: Jagoda Górska
license: GPL-3
homepage: https://github.com/juliagoda/givenfind
git: git@github.com:givenfind/givenfind.git
extra-source-files: README.md
dependencies:
  - base >=4.8 && <5
  - text >=1.2 && <1.3
  - containers >=0.5 && <0.6
  - reverse-geocoding >=0.3 && <0.4
  - gps >=1.2 && <1.3
  - split >=0.2 && <0.3
  - time >=1.6 && <1.7
  - radium >= 0.8.0
library:
  source-dirs: src
  dependencies:
    - base >=4.8 && <5
    - text >=1.2 && <1.3
    - containers >=0.5 && <0.6

tests:
  hadolint-unit-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base
      - givenfind
      - QuickCheck
